import { cn } from "@/lib/utils";
import "@/assets/css/globals.css";
import type { Metadata } from "next";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { Toaster } from "@/components/ui/sonner";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { DirectionProvider } from "@/components/ui/direction";
import { Inter, Playfair_Display, Cairo } from "next/font/google";
import GoogleAuthProvider from "@/providers/google-auth-provider";

const InterFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const PlayfairDisplayFont = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const CairoFont = Cairo({
  variable: "--font-cairo",
  subsets: ["arabic"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: {
    default: "Blúme Petals",
    template: "Blúme Petals - %s",
  },
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    return notFound();
  }

  const dir = locale === "ar" ? "rtl" : "ltr";

  return (
    <html
      lang={locale}
      dir={dir}
      className={cn(
        InterFont.variable,
        PlayfairDisplayFont.variable,
        CairoFont.variable,
        "h-full antialiased",
      )}
    >
      <GoogleAuthProvider>
        <NextIntlClientProvider>
          <DirectionProvider dir={dir}>
            <body className="min-h-full flex flex-col">
              <NuqsAdapter>
                {children}
                <Toaster richColors />
              </NuqsAdapter>
            </body>
          </DirectionProvider>
        </NextIntlClientProvider>
      </GoogleAuthProvider>
    </html>
  );
}
